{% set name = "grib2io" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-MDL/grib2io/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d719fb71c36ad80a1a3429f598e59df6a55059dc7025c52fd054cc7490453c54

build:
  skip: true  # [win or py<38]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --config-settings=cmake.define.GRIB2IO_WITH_IP=ON -vv"

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]

  host:
    - python
    - pip
    - scikit-build-core
    - cython
    - numpy
    - nceplibs-g2c
    - nceplibs-ip >=5.1.0

  run:
    - python
    - numpy
    - pyproj
    - nceplibs-g2c
    - nceplibs-ip >=5.1.0

test:
  imports:
    - grib2io
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NOAA-MDL/grib2io
  summary: Python interface to the NCEP G2C Library for reading/writing GRIB2 files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - EricEngle-NOAA
