{% set name = "grib2io" %}
{% set version = "2.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-MDL/grib2io/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 49bf52c47eea213463724c909370c7b1f804602524f9cbde4ff9ff5ce79109ab

build:
  skip: true  # [win or py<38]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --config-settings=cmake.define.GRIB2IO_WITH_IP=ON --config-settings=cmake.args=-GNinja"

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]

  host:
    - python
    - pip
    - scikit-build-core
    - cython
    - numpy
    - nceplibs-g2c
    - nceplibs-ip >=5.1.0

  run:
    - python
    - numpy
    - pyproj
    - nceplibs-g2c
    - nceplibs-ip >=5.1.0

test:
  imports:
    - grib2io
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NOAA-MDL/grib2io
  summary: Python interface to the NCEP G2C Library for reading/writing GRIB2 files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - EricEngle-NOAA
